// <auto-generated />
using System;
using Event_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Event_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Event_Management_System.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(149)
                        .HasColumnType("nvarchar(149)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "karim.ibrahim@example.com",
                            FullName = "Karim Ibrahim",
                            Phone = "+201301234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "layla.ahmad@example.com",
                            FullName = "Layla Ahmad",
                            Phone = "+201401234567"
                        },
                        new
                        {
                            Id = 3,
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            Phone = "+201501234567"
                        },
                        new
                        {
                            Id = 4,
                            Email = "noor.hassan@example.com",
                            FullName = "Noor Hassan",
                            Phone = "+201601234567"
                        },
                        new
                        {
                            Id = 5,
                            Email = "salma.sayed@example.com",
                            FullName = "Salma Sayed",
                            Phone = "+201701234567"
                        },
                        new
                        {
                            Id = 6,
                            Email = "hassan.amin@example.com",
                            FullName = "Hassan Amin",
                            Phone = "+201801234567"
                        });
                });

            modelBuilder.Entity("Event_Management_System.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(499)
                        .HasColumnType("nvarchar(499)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1000,
                            Category = "Technology",
                            Description = "Annual technology conference featuring latest innovations in AI and cloud computing",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Tech Conference 2025",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 500,
                            Category = "Business",
                            Description = "Exclusive networking event for business professionals and entrepreneurs",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EventDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Business Networking Summit",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 300,
                            Category = "Marketing",
                            Description = "Intensive workshop on modern digital marketing strategies and tools",
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            EventDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            Title = "Digital Marketing Workshop",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 200,
                            Category = "Training",
                            Description = "Comprehensive leadership training for mid-level and senior management",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            EventDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 9, 30, 0, 0),
                            Title = "Leadership Development Program",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 400,
                            Category = "Technology",
                            Description = "48-hour hackathon for developers and innovators to build solutions",
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            EventDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Title = "Innovation Hackathon",
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("Event_Management_System.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(149)
                        .HasColumnType("nvarchar(149)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.mohamed@example.com",
                            FullName = "Ahmed Mohamed",
                            Phone = "+201001234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatima.hassan@example.com",
                            FullName = "Fatima Hassan",
                            Phone = "+201101234567"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mohammed.ali@example.com",
                            FullName = "Mohammed Ali",
                            Phone = "+201201234567"
                        });
                });

            modelBuilder.Entity("Event_Management_System.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId", "EventId")
                        .IsUnique();

                    b.HasIndex("EventId", "AttendeeId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendeeId = 1,
                            EventId = 1,
                            RegistrationDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AttendeeId = 2,
                            EventId = 1,
                            RegistrationDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            AttendeeId = 3,
                            EventId = 2,
                            RegistrationDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 4,
                            AttendeeId = 4,
                            EventId = 2,
                            RegistrationDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            AttendeeId = 5,
                            EventId = 3,
                            RegistrationDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 6,
                            AttendeeId = 1,
                            EventId = 4,
                            RegistrationDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 7,
                            AttendeeId = 2,
                            EventId = 5,
                            RegistrationDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 8,
                            AttendeeId = 6,
                            EventId = 5,
                            RegistrationDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("Event_Management_System.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("nvarchar(99)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5000,
                            Location = "Cairo, Egypt",
                            Name = "Grand Convention Center"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2000,
                            Location = "Alexandria, Egypt",
                            Name = "Marina Event Hall"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3000,
                            Location = "Giza, Egypt",
                            Name = "Giza Exhibition Complex"
                        });
                });

            modelBuilder.Entity("Event_Management_System.Models.Event", b =>
                {
                    b.HasOne("Event_Management_System.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Event_Management_System.Models.Registration", b =>
                {
                    b.HasOne("Event_Management_System.Models.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Event_Management_System.Models.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Event_Management_System.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Event_Management_System.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Event_Management_System.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
